# Generated by Django 3.0.3 on 2020-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0008_auto_20200305_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='faves',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipebox.Recipe'),
        ),
    ]
